config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ######## Authentication Routes ########
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"


  ######## Application Routes ########
  root "main#index"

  resources :url_creations, only: [:index, :new, :create, :redirect, :show] do
    resources :short_urls, only: [:new, :create] do
      resources :geolocations, only: [:new, :create]
    end
  end

  get '/:short_path/stats', to: "url_creations#show"
  get "/:short_path", to: "url_creations#redirect"
  post "update_num_clicks", to: "url_creations#update_num_clicks"
  
  # error page
  get "error", to: "main#error"

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if Current.user
            redirect_to new_url_creation_path
        end
    end

    def error
    end
end

app/views/main/error.html.erb
<div class="container">

  <div class="px-4 py-5 text-center">
    <div class="display-6 mb-5">Oops! You bumped into the wrong place.</div>

    <%= link_to "Shorten a URL", new_url_creation_path, class: "btn btn-primary" %>

  </div>    

</div>

app/views/main/index.html.erb
<div class="container">

    <div class="px-4 py-5 text-center">
        <h1 class="fw-bold">URLs are better shorter.</h1>

        <% if Current.user %>

            <%= render "urls_creations#new" %>

        <% else %>

            <div class="d-grid gap-2 col-7 col-lg-3 mx-auto my-5">
                <%= link_to "Sign Up", sign_up_path, class: "btn btn-primary px-5" %>
                <%= link_to "Sign In", sign_in_path, class: "btn btn-primary px-5" %>
            </div>

        <% end %>
    </div>

</div>  