config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ######## Authentication Routes ########
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"


  ######## Application Routes ########
  root "main#index"

  resources :url_creations, only: [:index, :new, :create, :redirect, :show] do
    resources :short_urls, only: [:new, :create] do
      resources :geolocations, only: [:new, :create]
    end
  end

  get '/:short_path/stats', to: "url_creations#show"
  get "/:short_path", to: "url_creations#redirect"
  post "update_num_clicks", to: "url_creations#update_num_clicks"
  
  # error page
  get "error", to: "main#error"

end

app/controllers/url_creations_controller.rb
require 'open-uri'
require 'nokogiri'

class  UrlCreationsController < ApplicationController
    before_action :require_user_signed_in!
    after_action :get_geolocation, :update_num_clicks, only: [:redirect]

    def index
        # get all urls for current user
        @target_urls = TargetUrl.where(user_id: Current.user.id)
    end

    def new
        @target_url = TargetUrl.new
    end

    def create
        # Find an existing TargetUrl with the specified target_url or initialise a new one if none exists
        @target_url = TargetUrl.find_or_initialize_by(user_id: Current.user.id, target_url: url_params[:target_url])
        @target_url.user_id = Current.user.id
        @target_url.title_tag = get_title_tag(url_params[:target_url])

        # If the TargetUrl object is new, save it to the database
        if @target_url.new_record?
          @target_url.save
        end
      
        @custom_slug = url_params[:custom_slug]
      
        # If a custom slug was specified in the form submission
        if @custom_slug.present?

            if !valid_short_path?(@custom_slug)
                flash[:danger] = "Invalid custom slug. Only alphanumeric characters are allowed and it must be within 6 to 15 characters."
                # @target_url.errors.add(:base, "Invalid custom slug. Only alphanumeric characters are allowed and it must be within 6 to 15 characters.")
                redirect_to new_url_creation_path(target_url: @target_url.target_url, custom_slug: @custom_slug)


            elsif duplicate_short_path_exists?(@custom_slug)
                flash[:danger] = "A shortened URL with the same custom slug is taken. Please try again."
                # @target_url.errors.add(:base, "A shortened URL with the same custom slug is taken. Please try again.")
                redirect_to new_url_creation_path(target_url: @target_url.target_url, custom_slug: @custom_slug)

            else

                if @target_url.save
                    @short_url = @target_url.short_urls.build(short_path: @custom_slug)

                    if @short_url.valid?
                        @short_url.save
                        redirect_to url_creations_path, notice: "Your URL has been shortened!"
                    else
                        @target_url.errors.add(:base, "There was an error while creating the short URL. Please try again.")
                        render :new
                    end

                else
                    @target_url.errors.add(:base, "There was an error while creating the short URL. Please try again.")
                    render :new

                end
            end
        else
          
            if @target_url.save
                @short_url = @target_url.short_urls.build(short_path: generate_random_short_path)

                if @short_url.valid?
                    @short_url.save
                    redirect_to url_creations_path, notice: "Your URL has been shortened!"
                else
                    @target_url.errors.add(:base, "There was an error while creating the short URL. Please try again.")
                    render :new
                end
            else
                @target_url.errors.add(:base, "There was an error while creating the short URL. Please try again.")
                render :new
            end
        end
        
      rescue ActiveRecord::RecordInvalid => e
        # If there was an error while saving the TargetUrl or ShortUrl record, add the error message to the TargetUrl object's errors and render the 'new' view
        @target_url.errors.add(:target_url, e.message)
        render :new
      end
      

    def redirect
        # find short url
        @short_url = ShortUrl.find_by(short_path: params[:short_path])

        # if short url exists, redirect to target url
        if @short_url.present?
            @target_url = TargetUrl.find_by(id: @short_url.target_url_id)
            redirect_to @target_url.target_url, allow_other_host: true
            return

        else
            # if short url does not exist, render error page
            render 'main/error'
        end
    end

    def show
        @short_url = ShortUrl.find_by(short_path: params[:id])
    end

    private

        # Check valid short path of minimum 6 chars and maximum 15 chars with only alphanumeric characters
        def valid_short_path?(short_path)
            if (short_path.length >= 6 && short_path.length <= 15 && short_path.match?(/\A[a-zA-Z0-9]+\z/))
                true
            else
                false
            end
        end

        # Check for duplicate short path
        def duplicate_short_path_exists?(short_path)
            if ShortUrl.find_by(short_path: short_path).present?
                true
            else
                false
            end
        end

        # Generate random short path
        def generate_random_short_path
            short_path = SecureRandom.hex(3)
            if duplicate_short_path_exists?(short_path)
                generate_random_short_path
            else
                short_path
            end
        end

        # Increment and update number of clicks on short url
        def update_num_clicks
            if @short_url.present?
                @short_url.increment!(:num_clicks)
            end
        end

        # Retrieve geolocation of user
        def get_geolocation
            # use Geocoder gem
            if @short_url.present?
                city = request.location.city
                country = request.location.country
                @short_url.geolocation.create(city: city, country: country)
            end
        end

        # Retrieve title tag of URL
        def get_title_tag(url)
            begin
                doc = Nokogiri::HTML(URI.open(url))
                title_tag = doc.at_css("title").text
            rescue => e
                title_tag = "(No title found)"
            end

        end


        def url_params
            params.require(:target_url).permit(:target_url, :custom_slug)
        end
end

app/views/url_creations/index.html.erb
<div class="container">

    <% if @target_urls.length == 0 %>
      <div class="px-4 py-5 text-center">
          <div class="display-6 mb-5">No URLs shortened yet. Try it now!</div>
      </div>    
    <% end %>

    <%= render partial: "shared/shorten_url_button" %>


  <table class="table">
    <thead>
      <tr>
        <th scope="col" style="width: 30%">Original URL</th>
        <th scope="col" style="width: 40%">Title tag</th>
        <th scope="col" style="width: 20%">Short URL</th>
        <th scope=" col"style="width: 10%">Stats</th>
      </tr>
    </thead>
    <tbody>
      <% @target_urls.each do |target_url| %>
        <% target_url.short_urls.each do |short_url| %>
          <tr>     
            <% if target_url.short_urls.first == short_url %>
              <td rowspan="<%= target_url.short_urls.count %>" style="word-break: break-all;"><%= link_to target_url.target_url, target_url.target_url %></td>
              <td rowspan="<%= target_url.short_urls.count %>"><%= target_url.title_tag %></td>
            <% end %>            
            <td>
              <%= link_to URI.join(root_url, short_url.short_path).to_s, URI.join(root_url, short_url.short_path).to_s, target: :_blank, class: "btn btn-light" %>
            </td>   
            <td>
              <%= link_to url_creation_path(short_url.short_path) , class: "btn btn-info rounded-circle" do %>
                <i class="fa-sharp fa-solid fa-file-lines"></i>
              <% end %>
            </td>
          </tr>
        <% end %>


      <% end %>
      
    </tbody>
  </table>
</div>

app/views/url_creations/new.html.erb
<div class="container">

    <div class="px-4 py-5 text-center row justify-content-center">
        <p class="display-5 fw-bold">URLs are better shorter.</p>

        <%= form_with model: @target_url, url: url_creations_path, method: :post, class: "col col-lg-6" do |form|  %>
           <% if form.object.errors.any? %>
                <div class="alert alert-danger">
                    <% form.object.errors.full_messages.each do |message| %>
                        <div><%= message %></div>
                    <% end %>
                </div>
            <% end %>

            <div class="mt-5 mb-3">
                <%= form.text_field :target_url, class: "form-control", placeholder: "Enter your long URL", required: true %>
            </div>

            <div class="mb-5">
                <%= form.text_field :custom_slug, class: "form-control", placeholder: "Enter your custom slug (optional)" %>
            </div>

            <%= form.submit "Shorten URL", data: { turbo: false }, class: "btn btn-primary" %>
        <% end %>
    </div>

    

</div>

app/views/url_creations/show.html.erb
<div class="container">

    <%= render partial: "shared/shorten_url_button" %>

    <ul class="list-group mb-5">
        <li class="list-group-item">
            Short URL: <%= link_to URI.join(root_url, @short_url.short_path).to_s, URI.join(root_url, @short_url.short_path).to_s, target: :_blank, class: "btn btn-light" %>
        </li>
        <li class="list-group-item">
            Original URL: <%= link_to @short_url.target_url.target_url, @short_url.target_url.target_url, style: "word-break: break-all;" %>
        </li>
        <li class="list-group-item">
            Number of clicks: <%= @short_url.num_clicks %>
        </li>
    </ul>
    

    <% if @short_url.num_clicks == 0 %>
        <div class="alert alert-warning" role="alert">
            This short URL has no clicks yet.
        </div>
    <% else %>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">City</th>
                    <th scope="col">Country</th>
                    <th scope="col">Timestamp</th>
                </tr>
            </thead>
            <tbody>
                <% @short_url.geolocation.each do |short_url| %>
                    <tr>
                        <td><%= short_url.city %></td>
                        <td><%= short_url.country %></td>
                        <td><%= short_url.created_at %></td>
                    </tr>
                <% end %>
            
            </tbody>
    </table>
    <% end %>

    
</div>