config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ######## Authentication Routes ########
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"


  ######## Application Routes ########
  root "main#index"

  resources :url_creations, only: [:index, :new, :create, :redirect, :show] do
    resources :short_urls, only: [:new, :create] do
      resources :geolocations, only: [:new, :create]
    end
  end

  get '/:short_path/stats', to: "url_creations#show"
  get "/:short_path", to: "url_creations#redirect"
  post "update_num_clicks", to: "url_creations#update_num_clicks"
  
  # error page
  get "error", to: "main#error"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            # @user.generate_password_token!
            PasswordMailer.with(user: @user).reset.deliver_now
        ### For security reasons, we don't want to tell the user if the email address was found or not.
        # else
        #     flash[:alert] = "We could not find a user with that email address."
        #     render :new
        end

        redirect_to root_path, notice: "If an account with that email is found, we have sent you an email with instructions to reset your password."
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")

        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to sign_in_path, alert: "Your token has expired. Please try again."
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in again."
        else
            render :edit
        end
    end

    private 
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/password_resets/edit.html.erb
<% content_for :use_form_layout do %>
    
    <div>
        <% content_for :form_title do %>
            Reset your password
        <% end %>
    
        <% content_for :form_subtitle do %>
            Set a secure password that is easy to remember but hard to crack.
        <% end %>
    
        <% content_for :form_body do %>
            <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), class: "col col-12 col-lg-6", local: true do |form| %>
                <% if form.object.errors.any? %>
                    <div class="alert alert-danger">
                        <% form.object.errors.full_messages.each do |message| %>
                            <div><%= message %></div>
                        <% end %>
                    </div>
                <% end %>
                
                <div class="mb-3">
                    <%= form.label :password %>
                    <%= form.password_field :password, class: "form-control", placeholder: "Enter your password", required: true %>
                </div>

                <div class="mb-5">
                    <%= form.label :password_confirmation %>
                    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Re-enter your password", required: true %>
                </div>

                <div class="d-flex justify-content-center">
                    <%= form.submit "Reset Password", data: { turbo: false }, class: "btn btn-primary" %>
                </div>
            <% end %>
        <% end %>
    </div>
        
<% end %>

app/views/password_resets/new.html.erb
<% content_for :use_form_layout do %>
    
    <div>
        <% content_for :form_title do %>
            Forgot your password?
        <% end %>
    
        <% content_for :form_subtitle do %>
            Forgot your password? We've got your back!
        <% end %>
    
        <% content_for :form_body do %>
            <%= form_with url: password_reset_path, class: "col col-12 col-lg-6", local: true do |form| %>
                <div class="mb-5">
                    <%= form.label :email %>
                    <%= form.text_field :email, class: "form-control", placeholder: "Enter your email", required: true %>
                </div>

                <div class="d-flex justify-content-center mb-5">
                    <%= form.submit "Reset Password", data: { turbo: false }, class: "btn btn-primary px-5" %>
                </div>
            <% end %>

            <%= link_to "Go back", :back, class: "text-secondary" %>

        <% end %>
    </div>
        
<% end %>