config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ######## Authentication Routes ########
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"


  ######## Application Routes ########
  root "main#index"

  resources :url_creations, only: [:index, :new, :create, :redirect, :show] do
    resources :short_urls, only: [:new, :create] do
      resources :geolocations, only: [:new, :create]
    end
  end

  get '/:short_path/stats', to: "url_creations#show"
  get "/:short_path", to: "url_creations#redirect"
  post "update_num_clicks", to: "url_creations#update_num_clicks"
  
  # error page
  get "error", to: "main#error"

end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

<% if flash[:danger] %>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:danger] %>
    </div>
<% end %>

app/views/shared/_go_shorten_url_button.html.erb
<div class="py-5 text-center">

    <%= link_to "Shorten new URL", new_url_creation_path, class: "btn btn-primary" %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary px-3">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= content_tag :i, '', class: 'fa-solid fa-link' %>
      URL Shortener
    <% end %>

    <% if Current.user%>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-center align-items-center">
          <li class="nav-item">
              <%= link_to url_creations_path, class: 'nav-link' do %>
                <%= content_tag :i, '', class: 'fa-solid fa-book me-1' %>
                My Links
              <% end %> 
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex justify-content-center align-items-center">
          <li class="nav-item me-2 m">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-primary px-3" %>
          </li>
        </ul>
        
      </div>
    <% end %>       

  </div>
</nav>

app/views/shared/_shorten_url_button.html.erb
<div class="py-5 text-center">

    <%= link_to "Shorten new URL", new_url_creation_path, class: "btn btn-primary" %>

</div>